apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Example configuration for the webserver
# at https://github.com/johnwesonga/k8s-playground-server

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
labels:
- includeSelectors: true
  pairs:
    app: k8s-playground-server
