apiVersion: v1
kind: Service
metadata:
  name: k8s-playground
  labels:
    run: k8s-playground
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: k8s-playground
